security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        main:
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_homepage  # Ruta a la que ir cuando el login es exitoso
                failure_path: app_login  # Redirigir al login si las credenciales son incorrectas

        # Otros firewalls que puedas tener...
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuración de la autenticación
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
