controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_delete_profile:
    path: /profile/{username}/delete
    controller: App\Controller\ProfileController::delete
    methods: [POST]


    
